### ISSUE TITLE
Reader doesn’t show anything

### ISSUE THREAD

**Issue by Tacosteak2022** [ravgeetdhillon/notion-feeder#14]
Hi,

Yesterday I ran everything and it was fine. Today, I tried to run the workflow mannually but nothing showed up in the reader section. Could someone explain to me what happens?

Thanks

**Comment by ravgeetdhillon** [comment]
Hey @Tacosteak2022, I have checked your Actions logs. It says that Database ID not found. This means that either you have entered wrong database ID or you have not shared the database with the integration in Notion.

**Comment by ravgeetdhillon** [comment]
I am closing this since it is not related to Notion Feeder itself.
