### ISSUE TITLE
Possible Rootkit?

### ISSUE THREAD

**Issue by heycarissa** [ravgeetdhillon/notion-feeder#19]
I forked this repository 4 days before getting a rootkit & am wondering if the [index](https://raw.githubusercontent.com/ravgeetdhillon/notion-feeder/build/dist/index.js) could have something to do with it? Was this code built by you @ravgeetdhillon?

**Comment by ravgeetdhillon** [comment]
Yup. It's is built entirely by GitHub Actions. Here is the [script](https://github.com/ravgeetdhillon/notion-feeder/blob/master/.github/workflows/release.yml) that creates the release.

**Comment by heycarissa** [comment]
Why are you data logging everything? Why do you need access to endpoints? Vmessages? iCloud? Email? Forbidden Host Code Point? Ipv4...

**Comment by ravgeetdhillon** [comment]
I don't agree with the claims you have raised. The code is open source. You can take a look at what's going on. I'm going to close this issue for now as it is out of topic for this project.
