### ISSUE TITLE
How to test or trigger manually?

### ISSUE THREAD

**Issue by jay377** [ravgeetdhillon/notion-feeder#2]
Hello,

Thank you for this very potentially useful tool!
I followed all your instructions but know nothing about git or code.

I assume I had to create repository secret not environment secret?

Then I also assume that I had to enable actions under workflows, that was not mentioned.

So if this is all done it will automatically just work once a day?
Is there a way to trigger it manually to test it out
 I dont know if i set it up correctly, do I just wait a day and see if feed contents show up?

Please advise. Thanks!

**Comment by ravgeetdhillon** [comment]
This may help
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
.

Thanks for using the product. I'll update the README for better
instructions.

Thanks.

Ravgeet Dhillon
Full Stack Developer and Technical Content Writer
Website <https://www.ravgeet.in/> • LinkedIn
<https://linkedin.com/in/ravgeetdhillon> • Twitter
<https://twitter.com/ravgeetdhillon> • Blog <https://blog.ravgeet.in/> •
Newsletter <https://www.ravsam.in/newsletter/>

**Comment by ravgeetdhillon** [comment]
I have updated the README. Let me know if that helps.
