### ISSUE TITLE
Why will previously published entries be published repeatedly in the next RSS update？

### ISSUE THREAD

**Issue by vansun1992** [ravgeetdhillon/notion-feeder#26]
Why will previously published entries be published repeatedly in the next RSS update？

**Comment by ravgeetdhillon** [comment]
@vansun1992 Can you explain the issue better, like provide some evidence in the form of screenshots?

**Comment by vansun1992** [comment]
Maybe it's because I set the update too frequently. On average, the entries of each feed will appear repeatedly more than a dozen times. （Add one for each feed update）
If I restore the update frequency to once a day, will this phenomenon disappear?
![image](https://user-images.githubusercontent.com/56790653/180751406-2b343e6b-9465-47dd-b748-9c639f4741eb.png)

**Comment by ravgeetdhillon** [comment]
@vansun1992 Yup. You are right. Currently, the app supports only once-a-day updates.

**Comment by ravgeetdhillon** [comment]
I'm going to close the issue as it is out of the context of the current app. In case you have any more questions, do let me know.
