### ISSUE TITLE
How to self-host it on my server (Vultr, GCP etc)? 

### ISSUE THREAD

**Issue by cnscorpions** [ravgeetdhillon/notion-feeder#29]
Very an awesome project.

But is there any guide on how to self-host on my server?

Thanks

**Comment by ravgeetdhillon** [comment]
@cnscorpions If you see the [release](https://github.com/ravgeetdhillon/notion-feeder/blob/master/.github/workflows/release.yml) script, you can get plenty of information on how to build the project. Here is the [build](https://github.com/ravgeetdhillon/notion-feeder/tree/build) output. You can deploy the `dist` directory to your server and run it using CRON jobs.

**Comment by cnscorpions** [comment]
Thanks, I'll try it later.
