### ISSUE TITLE
Not work in Notion

### ISSUE THREAD

**Issue by darkwayder** [ravgeetdhillon/notion-feeder#3]
Hello.

Thank you for this very potentially useful tool!

I followed all your instructions but not work in "Notion".  I don’t understand what I’m doing wrong

I understand that it should work without "Node". It is required to install "Node" and clone repo?

Please advise. Thanks!

**Comment by ravgeetdhillon** [comment]
Hi @darkwayder, I have updated the README with better instructions. Let me know if it helps.

**Comment by darkwayder** [comment]
Thanks. Everything works.

Can be added to README:

point 9. Click on the Get Feed action in the left panel and then click "Run workflow"
and select Branch: patch-1 and click "Run workflow". 
 
I understand that the update is triggered by time in the script but for the first run it needs to be explained. Request for opinion.
