### ISSUE TITLE
Update Feed

### ISSUE THREAD

**Issue by darkwayder** [ravgeetdhillon/notion-feeder#4]
Is it possible to update the feed more than once. For example every hour or 2 hours?

**Comment by ravgeetdhillon** [comment]
It is not currently possible but I can add this feature.

**Comment by darkwayder** [comment]
Thanks. It would be nice.

I tried changing in the main.yml file for different options. One hour, two hours. Everything works, but old news is duplicated.
![Update feed](https://user-images.githubusercontent.com/63612833/141144577-ee3b17f4-c372-4f96-9075-5c981c5b01b1.png)

**Comment by Pacman99** [comment]
I was running into this too, so I wrote some code to prevent duplicates. I was able to make it pretty efficient, just adds one more API call in throughout the script run to get a list of all matching pages.
Here is the commit for that https://github.com/Pacman99/notion-feeder/commit/5ca333b159319a164ad713f8cf256a6694de31d5

**Comment by grinor** [comment]
Hi @Pacman99 I tried your commit in my fork seems not working, still duplicates coming
