### ISSUE TITLE
Image URL regex is too strict

### ISSUE THREAD

**Issue by Pacman99** [ravgeetdhillon/notion-feeder#7]
For the website axios.com, their image urls have an `=` symbol in them and this doesn't get matched in the imageUrl regex, so they just get forwarded as links. I fixed this in my fork with this commit, https://github.com/Pacman99/notion-feeder/commit/3a65a5de4cfa07066f2a65ec3083de436a791cad. But I'm not sure if its the best solution, since I just replaced the middle part with `.*`. I can send a PR if that sounds like a good solution, but either way this is a problem with some websites.

**Comment by ravgeetdhillon** [comment]
Fixed in #10
